package com.gdxsoft.ai.test;

import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Statement;

import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.gdxsoft.ai.modes.Modes;
import com.gdxsoft.easyweb.conf.ConnectionConfigs;
import com.gdxsoft.easyweb.data.DTTable;
import com.gdxsoft.easyweb.datasource.DataConnection;
import com.gdxsoft.easyweb.script.RequestValue;

/**
 * 集成测试数据库管理器
 * <p>
 * 使用 ewa_conf.xml 中配置的 HSQLDB 内存数据库，测试完自动销毁。
 * 从 ai_settings.json 读取 AI provider 配置。
 */
public class TestDatabase {
    private static final Logger LOGGER = LoggerFactory.getLogger(TestDatabase.class);

    // 使用 ewa_conf.xml 中定义的 HSQLDB 配置名称
    public static final String DB_CONFIG_NAME = "test_hsqldb";

    private static boolean initialized = false;
    private static JSONObject aiSettings;

    /**
     * 初始化数据库：建表 + 插入 provider 配置
     */
    public static synchronized void init() throws Exception {
        if (initialized) {
            return;
        }

        LOGGER.info("初始化 HSQLDB 内存数据库...");

        // 1. 触发框架加载 ewa_conf.xml
        ConnectionConfigs configs = ConnectionConfigs.instance();
        if (configs == null || !configs.containsKey(DB_CONFIG_NAME)) {
            throw new RuntimeException("未找到数据库配置: " + DB_CONFIG_NAME + "，请检查 ewa_conf.xml");
        }
        LOGGER.info("已加载数据库配置: {}", DB_CONFIG_NAME);

        // 2. 建表
        createTables();

        // 3. 加载配置
        loadSettings();

        // 4. 插入 provider 配置
        insertProviderConfigs();

        // 5. 加载测试 Mode 配置
        loadTestModes();

        initialized = true;
        LOGGER.info("HSQLDB 初始化完成");
    }

    /**
     * 加载测试用的 Mode 配置
     */
    private static void loadTestModes() throws Exception {
        Modes modes = new Modes();
        String xml = new String(
            TestDatabase.class.getClassLoader().getResourceAsStream("test_mode.xml").readAllBytes(),
            java.nio.charset.StandardCharsets.UTF_8
        );
        modes.loadModes(xml);
        LOGGER.info("测试 Mode 配置加载完成");
    }

    /**
     * 创建所有需要的表
     */
    private static void createTables() throws Exception {
        String[] sqls = {
            // AI_CHAT - 聊天会话
            """
            CREATE TABLE AI_CHAT (
                AI_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                AI_UID VARCHAR(100),
                AI_PID BIGINT,
                AI_PROVIDER VARCHAR(50),
                AI_MODEL VARCHAR(100),
                AI_THINKING INT DEFAULT 0,
                AI_STREAM INT DEFAULT 1,
                AI_CUR_STEP VARCHAR(100),
                AI_MODE VARCHAR(100),
                AI_MAX_TOKEN INT,
                AI_CDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                AI_MDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                ADM_ID INT,
                USR_ID INT,
                SUP_ID INT
            )
            """,
            // AI_CHAT_MSG - 聊天消息
            """
            CREATE TABLE AI_CHAT_MSG (
                AIM_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                AI_ID BIGINT,
                AIM_MSG CLOB,
                AIM_ROLE VARCHAR(20),
                AIM_BY_USER INT DEFAULT 0,
                AIM_TIME_BEGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                AIM_TIME_END TIMESTAMP,
                AIM_STEP VARCHAR(100),
                AIM_ACTION VARCHAR(100),
                AIM_ACTION_CLASS VARCHAR(200),
                AIM_PROMPT_NAME VARCHAR(100),
                AIM_SKIP_APPEND INT DEFAULT 0,
                AIM_TOTAL_TOKENS BIGINT,
                AIM_COMPLETION_TOKENS BIGINT,
                AIM_PROMPT_TOKENS BIGINT
            )
            """,
            // AI_CHAT_PARAMS - 参数存储
            """
            CREATE TABLE AI_CHAT_PARAMS (
                AIP_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                AI_ID BIGINT,
                AIM_ID BIGINT,
                AIP_NAME VARCHAR(100),
                AIP_VAL VARCHAR(2000),
                AIP_TYPE VARCHAR(50)
            )
            """,
            // AI_PROVIDER - 提供商
            """
            CREATE TABLE AI_PROVIDER (
                AP_CODE VARCHAR(50) PRIMARY KEY,
                AP_NAME VARCHAR(100),
                AP_STATUS VARCHAR(20) DEFAULT 'USED'
            )
            """,
            // AI_PROVIDER_MODEL - 模型
            """
            CREATE TABLE AI_PROVIDER_MODEL (
                APM_CODE VARCHAR(100) PRIMARY KEY,
                AP_CODE VARCHAR(50),
                APM_NAME VARCHAR(100),
                APM_STATUS VARCHAR(20) DEFAULT 'USED'
            )
            """,
            // AI_PROVIDER_URL - API 地址和密钥
            """
            CREATE TABLE AI_PROVIDER_URL (
                APU_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                AP_CODE VARCHAR(50),
                APU_URL VARCHAR(500),
                APU_KEY VARCHAR(500),
                APU_STATUS VARCHAR(20) DEFAULT 'USED',
                APU_MDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        };

        DataConnection cnn = new DataConnection(DB_CONFIG_NAME, null);
        try {
            for (String sql : sqls) {
                cnn.executeUpdateNoParameter(sql);
            }
            LOGGER.info("数据库表创建完成");
        } finally {
            cnn.close();
        }
    }

    /**
     * 加载 ai_settings.json
     */
    private static void loadSettings() throws Exception {
        URL aiUrl = TestDatabase.class.getClassLoader().getResource("ai_settings.json");
        if (aiUrl != null) {
            String json = new String(Files.readAllBytes(Paths.get(aiUrl.toURI())), StandardCharsets.UTF_8);
            aiSettings = new JSONObject(json);
        } else {
            aiSettings = new JSONObject();
        }
        LOGGER.info("配置加载完成: ai_settings.json={}", aiSettings.length() > 0);
    }

    /**
     * 插入 provider 配置到数据库
     */
    private static void insertProviderConfigs() throws Exception {
        if (aiSettings == null || aiSettings.length() == 0) {
            LOGGER.warn("ai_settings.json 为空");
            return;
        }

        DataConnection cnn = new DataConnection(DB_CONFIG_NAME, null);
        try {
            for (String provider : aiSettings.keySet()) {
                if (provider.startsWith("_")) continue;

                JSONObject cfg = aiSettings.getJSONObject(provider);
                String apiUrl = cfg.optString("api_url", "");
                String model = cfg.optString("model", "");
                String apiKey = cfg.optString("api_key", "");

                if (apiUrl.isEmpty() || model.isEmpty()) {
                    LOGGER.info("跳过 {}: 缺少 api_url 或 model", provider);
                    continue;
                }

                if (apiKey.isEmpty()) {
                    LOGGER.info("跳过 {}: 未配置 API Key", provider);
                    continue;
                }

                // 插入 AI_PROVIDER (先删除再插入) - 使用小写以匹配查询
                cnn.executeUpdateNoParameter("DELETE FROM AI_PROVIDER WHERE AP_CODE = '" + provider + "'");
                String sqlProvider = String.format(
                    "INSERT INTO AI_PROVIDER (AP_CODE, AP_NAME, AP_STATUS) VALUES ('%s', '%s', 'USED')",
                    provider, provider);
                cnn.executeUpdateNoParameter(sqlProvider);

                // 插入 AI_PROVIDER_MODEL (先删除再插入) - 使用小写以匹配查询
                cnn.executeUpdateNoParameter("DELETE FROM AI_PROVIDER_MODEL WHERE APM_CODE = '" + model + "'");
                String sqlModel = String.format(
                    "INSERT INTO AI_PROVIDER_MODEL (APM_CODE, AP_CODE, APM_NAME, APM_STATUS) VALUES ('%s', '%s', '%s', 'USED')",
                    model, provider, model);
                cnn.executeUpdateNoParameter(sqlModel);

                // 插入 AI_PROVIDER_URL - 使用小写以匹配查询
                cnn.executeUpdateNoParameter("DELETE FROM AI_PROVIDER_URL WHERE AP_CODE = '" + provider + "'");
                String sqlUrl = String.format(
                    "INSERT INTO AI_PROVIDER_URL (AP_CODE, APU_URL, APU_KEY, APU_STATUS) VALUES ('%s', '%s', '%s', 'USED')",
                    provider, apiUrl, apiKey.replace("'", "''"));
                cnn.executeUpdateNoParameter(sqlUrl);

                LOGGER.info("已配置 provider: {} (model={})", provider, model);
            }
        } finally {
            cnn.close();
        }
    }

    /**
     * 获取数据库连接配置名
     */
    public static String getDbConfigName() {
        return DB_CONFIG_NAME;
    }

    /**
     * 创建 RequestValue 并设置基础参数
     */
    public static RequestValue createRequestValue() {
        RequestValue rv = new RequestValue();
        // 通过反射初始化空的 HTTP headers 避免 NullPointerException
        try {
            java.lang.reflect.Field field = RequestValue.class.getDeclaredField("httpHeaders");
            field.setAccessible(true);
            field.set(rv, new java.util.HashMap<String, String>());
        } catch (Exception e) {
            LOGGER.warn("初始化 httpHeaders 失败: {}", e.getMessage());
        }
        return rv;
    }

    /**
     * 查询 AI_CHAT_MSG 表中指定 AI_ID 的消息数量
     */
    public static int getMessageCount(long aiId) throws Exception {
        RequestValue rv = createRequestValue();
        rv.addOrUpdateValue("ai_id", aiId, "bigint", 100);
        String sql = "SELECT COUNT(*) AS CNT FROM AI_CHAT_MSG WHERE AI_ID = @ai_id";
        DTTable tb = DTTable.getJdbcTable(sql, DB_CONFIG_NAME, rv);
        if (tb.getCount() > 0) {
            long count = tb.getCell(0, "CNT").toLong();
            return (int) count;
        }
        return 0;
    }

    /**
     * 查询 AI_CHAT_MSG 表中指定角色的消息内容
     */
    public static String getMessageContent(long aiId, String role) throws Exception {
        RequestValue rv = createRequestValue();
        rv.addOrUpdateValue("ai_id", aiId, "bigint", 100);
        rv.addOrUpdateValue("role", role);
        String sql = "SELECT AIM_MSG FROM AI_CHAT_MSG WHERE AI_ID = @ai_id AND AIM_ROLE = @role ORDER BY AIM_ID DESC";
        DTTable tb = DTTable.getJdbcTable(sql, DB_CONFIG_NAME, rv);
        if (tb.getCount() > 0) {
            return tb.getCell(0, "AIM_MSG").toString();
        }
        return null;
    }

    /**
     * 检查 provider 是否已配置
     */
    public static boolean isProviderConfigured(String provider) {
        try {
            RequestValue rv = createRequestValue();
            rv.addOrUpdateValue("provider", provider.toLowerCase());
            String sql = "SELECT COUNT(*) AS CNT FROM AI_PROVIDER_URL WHERE AP_CODE = @provider AND APU_STATUS = 'USED'";
            DTTable tb = DTTable.getJdbcTable(sql, DB_CONFIG_NAME, rv);
            if (tb.getCount() > 0) {
                return tb.getCell(0, "CNT").toLong() > 0;
            }
        } catch (Exception e) {
            LOGGER.error("检查 provider 配置失败: {}", e.getMessage());
        }
        return false;
    }

    /**
     * 获取已配置的 provider 列表
     */
    public static String[] getConfiguredProviders() {
        try {
            String sql = "SELECT AP_CODE FROM AI_PROVIDER_URL WHERE APU_STATUS = 'USED'";
            DTTable tb = DTTable.getJdbcTable(sql, DB_CONFIG_NAME, createRequestValue());
            String[] providers = new String[tb.getCount()];
            for (int i = 0; i < tb.getCount(); i++) {
                providers[i] = tb.getCell(i, "AP_CODE").toString().toLowerCase();
            }
            return providers;
        } catch (Exception e) {
            LOGGER.error("获取 provider 列表失败: {}", e.getMessage());
            return new String[0];
        }
    }

    /**
     * 获取 AI 配置
     */
    public static JSONObject getAiSettings() {
        return aiSettings;
    }

    /**
     * 关闭数据库（HSQLDB 内存数据库会自动清理）
     */
    public static void shutdown() {
        try {
            DataConnection cnn = new DataConnection(DB_CONFIG_NAME, null);
            cnn.executeUpdateNoParameter("SHUTDOWN");
            cnn.close();
            LOGGER.info("HSQLDB 已关闭");
        } catch (Exception e) {
            LOGGER.warn("关闭数据库失败: {}", e.getMessage());
        }
        initialized = false;
    }
}
