-- 为 AI_CHAT 表添加关联引用字段
-- 执行日期: 2026-07-09

ALTER TABLE AI_CHAT ADD AI_REF VARCHAR(50);
ALTER TABLE AI_CHAT ADD AI_REF_ID VARCHAR(50);

-- 可选: 添加注释
COMMENT ON COLUMN AI_CHAT.AI_REF IS '关联引用类型';
COMMENT ON COLUMN AI_CHAT.AI_REF_ID IS '关联引用ID';
