-- =====================================================================
-- AI_VOICE_CLONE 系统内置音色初始化
-- ADM_ID=USR_ID=SUP_ID=0 标识为系统内置，AVC_PREFIX='system'
-- 幂等：已存在的 voice_id 不会重复插入
-- =====================================================================

-- Qwen-TTS
INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'Cherry', 'qwen_tts', 'qwen3-tts-flash', 'system', N'Qwen-TTS 默认女声', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'Cherry');

-- Qwen-Audio-TTS
INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'longanhuan_v3.6', 'qwen_tts', 'qwen-audio-3.0-tts-flash', 'system', N'Qwen-Audio-TTS 男声（支持情感标签）', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'longanhuan_v3.6');

-- CosyVoice
INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'longanyang', 'qwen_tts', 'cosyvoice-v3-flash', 'system', N'CosyVoice 男声', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'longanyang');

INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'longanhuan_v3', 'qwen_tts', 'cosyvoice-v3-flash', 'system', N'CosyVoice 男声（支持指令控制/方言）', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'longanhuan_v3');

INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'longshange_v3', 'qwen_tts', 'cosyvoice-v3-flash', 'system', N'CosyVoice 男声（支持方言）', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'longshange_v3');

-- MiniMax
INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'male-qn-qingse', 'minimax_tts', 'MiniMax/speech-2.8-hd', 'system', N'MiniMax 男声-青涩', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'male-qn-qingse');

-- Doubao
INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'zh_female_cancan_mars_bigtts', 'doubao_tts', 'seed-audio-1.0', 'system', N'豆包默认女声-灿灿', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'zh_female_cancan_mars_bigtts');

INSERT INTO AI_VOICE_CLONE (AVC_VOICE_ID, AVC_PROVIDER, AVC_TARGET_MODEL, AVC_PREFIX, AVC_DESC, AVC_STATUS, ADM_ID, USR_ID, SUP_ID, AVC_CDATE, AVC_MDATE)
SELECT 'zh_female_xiaohe_uranus_bigtts', 'doubao_tts', 'seed-tts-2.0', 'system', N'豆包女声-小荷（TTS 2.0）', 'USED', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AI_VOICE_CLONE WHERE AVC_VOICE_ID = 'zh_female_xiaohe_uranus_bigtts');
